export const data = [
    {
        id: "m5gr84i9",
        name: "TechCorp Soluciones",
        email: "contacto@techcorp.com",
        phone: "+1 (555) 123-4567",
        address: "123 Calle Tech, Silicon Valley, CA",
        industry: "Tecnología",
        employees: 150,
        revenue: 2500000,
        status: "active",
        createdAt: "2023-01-15",
        website: "https://techcorp.com",
        description: "Proveedor líder de soluciones de software empresarial"
    },
    {
        id: "3u1reuv4",
        name: "Green Energy Co",
        email: "info@greenenergy.com",
        phone: "+1 (555) 234-5678",
        address: "456 Avenida Renovable, Portland, OR",
        industry: "Energía",
        employees: 75,
        revenue: 1800000,
        status: "active",
        createdAt: "2022-08-22",
        website: "https://greenenergy.com",
        description: "Soluciones de energía sostenible para empresas modernas"
    },
    {
        id: "derv1ws0",
        name: "MediCare Plus",
        email: "soporte@medicareplus.com",
        phone: "+1 (555) 345-6789",
        address: "789 Boulevard Salud, Boston, MA",
        industry: "Salud",
        employees: 300,
        revenue: 4200000,
        status: "inactive",
        createdAt: "2021-11-10",
        website: "https://medicareplus.com",
        description: "Servicios integrales de gestión de salud"
    },
    {
        id: "5kma53ae",
        name: "FinanceFlow Inc",
        email: "hola@financeflow.com",
        phone: "+1 (555) 456-7890",
        address: "321 Wall Street, Nueva York, NY",
        industry: "Finanzas",
        employees: 200,
        revenue: 3500000,
        status: "active",
        createdAt: "2023-03-05",
        website: "https://financeflow.com",
        description: "Análisis financiero avanzado y consultoría"
    },
    {
        id: "bhqecj4p",
        name: "EduTech Academy",
        email: "aprende@edutech.com",
        phone: "+1 (555) 567-8901",
        address: "654 Calle Educación, Austin, TX",
        industry: "Educación",
        employees: 120,
        revenue: 1600000,
        status: "active",
        createdAt: "2022-12-18",
        website: "https://edutech.com",
        description: "Plataformas y herramientas de aprendizaje en línea innovadoras"
    },
    {
        id: "xyz789ab",
        name: "RetailMax Stores",
        email: "sales@retailmax.com",
        phone: "+1 (555) 678-9012",
        address: "987 Commerce Center, Chicago, IL",
        industry: "Retail",
        employees: 500,
        revenue: 8500000,
        status: "active",
        createdAt: "2020-05-12",
        website: "https://retailmax.com",
        description: "Multi-channel retail solutions and logistics"
    },
    {
        id: "def456cd",
        name: "CloudScale Systems",
        email: "cloud@cloudscale.com",
        phone: "+1 (555) 789-0123",
        address: "147 Cloud Drive, Seattle, WA",
        industry: "Computación en la Nube",
        employees: 85,
        revenue: 3200000,
        status: "inactive",
        createdAt: "2023-06-30",
        website: "https://cloudscale.com",
        description: "Enterprise cloud infrastructure and services"
    },
    {
        id: "ghi789ef",
        name: "AutoDrive Motors",
        email: "info@autodrive.com",
        phone: "+1 (555) 890-1234",
        address: "258 Innovation Way, Detroit, MI",
        industry: "Automotriz",
        employees: 800,
        revenue: 12000000,
        status: "active",
        createdAt: "2021-09-14",
        website: "https://autodrive.com",
        description: "Next-generation autonomous vehicle technology"
    },
    {
        id: "jkl012gh",
        name: "FoodChain Logistics",
        email: "logistics@foodchain.com",
        phone: "+1 (555) 901-2345",
        address: "369 Supply Chain Ave, Miami, FL",
        industry: "Logística",
        employees: 250,
        revenue: 2800000,
        status: "active",
        createdAt: "2022-04-08",
        website: "https://foodchain.com",
        description: "Smart logistics solutions for food industry"
    },
    {
        id: "mno345ij",
        name: "SecureNet Solutions",
        email: "security@securenet.com",
        phone: "+1 (555) 012-3456",
        address: "741 Cyber Security Blvd, San Francisco, CA",
        industry: "Ciberseguridad",
        employees: 180,
        revenue: 4100000,
        status: "inactive",
        createdAt: "2023-02-28",
        website: "https://securenet.com",
        description: "Advanced cybersecurity and threat protection"
    }
]